(ql:quickload :dbi)
(ql:quickload :clack)
(ql:quickload :lack)
(ql:quickload :lack-request)
(ql:quickload :lack-middleware-session)
(ql:quickload :lack-middleware-accesslog)
(ql:quickload :hunchentoot)
(ql:quickload :ironclad)
(load (merge-pathnames (make-pathname :directory '(:relative "./utils/string-util.lisp"))))
(load (merge-pathnames (make-pathname :directory '(:relative "./utils/datetime.lisp"))))
(load (merge-pathnames (make-pathname :directory '(:relative "./database/connection.lisp"))))
(load (merge-pathnames (make-pathname :directory '(:relative "./repositories/user-repository.lisp"))))
(load (merge-pathnames (make-pathname :directory '(:relative "./utils/file-util.lisp"))))
(load (merge-pathnames (make-pathname :directory '(:relative "./controllers/login-controller.lisp"))))
(load (merge-pathnames (make-pathname :directory '(:relative "./controllers/user-controller.lisp"))))
(load (merge-pathnames (make-pathname :directory '(:relative "./middlewares/auth-handler-middleware.lisp"))))
