(ql:quickload :dbi)
(ql:quickload :clack)
(ql:quickload :lack)
(ql:quickload :lack-request)
(ql:quickload :hunchentoot)
(load (merge-pathnames (make-pathname :directory '(:relative "./utils/datetime.lisp"))))
(load (merge-pathnames (make-pathname :directory '(:relative "./database/database.lisp"))))
(load (merge-pathnames (make-pathname :directory '(:relative "./utils/file-util.lisp"))))
(load (merge-pathnames (make-pathname :directory '(:relative "./controllers/user-controller.lisp"))))
